config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  root to: 'graduation_works#index'

  get '/login', to: 'sessions#new'

  resources :users, only: %i[] do
    collection do
      get 'edit'

      resource :me, me_scope: true, only: %i[] do
        resources :graduation_works, only: %i[index]
      end
    end
  end

  resources :graduation_works, only: %i[new edit show] do
    resources :reviews, only: %i[new edit]
  end

  draw(:api_v1)
end

app/controllers/raports_controller.rb
# frozen_string_literal: true

class RaportsController < ApplicationController
  include Pagy::Backend

  def index
    @search_params = permited_params
    scope = Raports::ScopeQuery.new(search_params: @search_params).call

    @pagy, @graduation_works = pagy(scope, items: 20)
  end

  def new; end

  def create
    redirect_to raports_path params: permited_params
  end

  def generate_csv
    scope = Raports::ScopeQuery.new(search_params: csv_params).call

    csv_data = GraduationWork.generate_csv(scope)
    send_data csv_data, filename: "Raport-#{Time.zone.today}.csv", disposition: :attachment
  end

  private

  def permited_params
    params.permit(:grade, :faculty, :date_from, :date_to, :evaluator, :supervisor, :field_of_study,
                  :key_word).to_unsafe_h.reject do |_k, v|
      v.empty?
    end
  end

  def csv_params
    params.require(:search_params).permit!.to_unsafe_h
  end
end

app/views/raports/index.html.erb
<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <div class="d-flex justify-content-between align-items-center activity">
                <div>
                    <span class="activity-done">
                        <% if params[:me_scope] %>
                           Yours
                        <% end %>
                        Graduations Work
                    </span>
                </div>
                <div class="icons">
                    <%= link_to 'Generate csv', generate_csv_raports_path(search_params: @search_params), method: :post %>
                </div>
            </div>
            <div class="mt-3">
                <ul class="list list-inline">
                    <% @graduation_works.each do |gd| %>
                        <li class="d-flex justify-content-between">
                            <div class="d-flex flex-row align-items-center">
                                <div class="ml-2">
                                    <h6 class="mb-0"><%= gd.title %></h6>
                                    <div class="d-flex flex-row mt-1 text-black-50 date-time">
                                        <div><span class="ml-2">Topic: <%= gd.topic %></span></div><br />
                                        <div><span class="ml-2">, Date of submission: <%= gd.date_of_submission.to_date %></span></div><br />
                                        <div class="ml-3"><span class="ml-2"><%=  %></span></div>
                                    </div>
                                </div>
                            </div>
                            <div class="d-flex flex-row align-items-center">
                                <div class="d-flex flex-column mr-2">
                                    <div class="profile-image"><%= button_to 'Details', graduation_work_path(gd), class: 'btn btn-primary', method: :get %></div>
                                </div>
                            </div>
                        </li>
                    <% end %>
                </ul>
            </div>
            <div class="d-flex justify-content-between align-items-center activity">
                <div><span class="activity-done"></span></div>
                <div class="icons"><%== pagy_nav(@pagy) %></div>
            </div>
        </div>
    </div>
</div>

app/views/raports/new.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="index-content">
    <div class="container">
            <div href="blog-ici.html" class="w-100">
                <div class="card">
                    <div class="mb-5 d-flex justify-content-between">
                        <div class="container rounded bg-white mt-5 mb-5">
                            <div class="row">
                                <div class="col-md-4 border-right">
                                    <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                                        <img class="rounded-circle mt-5" width="150px" src="https://media.istockphoto.com/vectors/business-report-icon-isolated-on-white-background-vector-id1359860011?b=1&k=20&m=1359860011&s=170667a&w=0&h=o4D_d9byQUfyCHgPKjiTYhLbif1Sl_iaFJprWvL22jA=">
                                            <span class="font-weight-bold"></span>
                                            <span class="text-black-50"></span>
                                            <span> </span>
                                    </div>
                                </div>
                                <div class="col-md-8 border-right">
                                    <div class="p-3 py-5">
                                        <div class="d-flex justify-content-between align-items-center mb-3">
                                            <h4 class="text-right">Generate raport</h4>
                                        </div>
                                        <%= form_with url: raports_path do |f| %>
                                            <div class="row mt-2">
                                                <div class="col-md-6">
                                                    <label class="labels">Faculty</label>
                                                    <%= f.text_field :faculty, class: 'form-control', placeholder: 'faculty' %>
                                                </div>
                                                <div class="col-md-6">
                                                    <label class="labels">Field of Study</label>
                                                    <%= f.text_field :field_of_study, class: 'form-control', placeholder: 'field of study' %>
                                                </div>
                                            </div>
                                            <div class="row mt-3">
                                                <div class="col-md-12">
                                                    <label class="labels">Key words</label>
                                                    <%= f.text_field :key_word, class: 'form-control', placeholder: 'Key words' %>
                                                </div>
                                                <div class="row mt-2">
                                                    <div class="col-md-6">
                                                        <label class="labels">Date from:</label>
                                                        <%= f.date_field :date_from, class: 'form-control' %>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <label class="labels">Date to:</label>
                                                        <%= f.date_field :date_to, class: 'form-control' %>
                                                    </div>
                                                </div>                                                
                                                <div class="col-md-12">
                                                    <label class="labels">Grade</label><br />
                                                    <%= f.select :grade, 
                                                    {
                                                        "Grade" => [
                                                            ['Select', nil],
                                                            ['5', 5.0],
                                                            ['4', 4.0],
                                                            ['3', 3.0],
                                                            ['2', 2.0]
                                                            ]
                                                    },
                                                    class: 'form-control'  %>
                                                </div>
                                                <div class="col-md-12">
                                                    <label class="labels">Supervisor email</label><br />
                                                    <%= f.text_field :supervisor, class: 'form-control', placeholder: 'supervisor email' %>
                                                </div>
                                                <div class="col-md-12">
                                                    <label class="labels">Evaluator email</label><br />
                                                    <%= f.text_field :evaluator, class: 'form-control', placeholder: 'evaluator email' %>
                                                </div>
                                            </div>
                                            <div class="mt-5 text-center">
                                                <%= f.submit 'Generate Raport', class: "btn btn-primary profile-button" %>
                                            </div>
                                        <% end %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>